queue_rules:
  - name: default

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Could you fix it @{{author}}?
  - name: github-actions
    conditions:
      - author=github-actions[bot]
      - files~=(bitrise.yml)
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        method: rebase
        name: default
  - name: Needs landing
    conditions:
      - label=Needs Landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Work In Progress
      - label!=Do Not Land
    actions:
      queue:
        method: merge
        name: default
