queue_rules:
  - name: duplicated default from Bitrise update - Auto Merge
    queue_conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=bitrise.yml
      - -files~=^(?!bitrise.yml).+$
      - head=update-br-new-xcode-version
    merge_conditions:
      - check-success=Bitrise
    merge_method: rebase
  - name: duplicated default from Rust Component Upgrade - Auto Merge
    queue_conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=Client.xcodeproj/project.pbxproj
      - files=Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
    merge_conditions:
      - check-success=Bitrise
    merge_method: rebase
  - name: duplicated default from L10N - Auto Merge
    queue_conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files~=^.+\.strings$
      - -files~=^(?!^.+\.strings).+$
    merge_conditions:
      - check-success=Bitrise
    merge_method: rebase
  - name: duplicated default from Needs landing - Rebase
    queue_conditions:
      - check-success=Bitrise
      - label=Needs Landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    merge_conditions:
      - check-success=Bitrise
    merge_method: rebase
  - name: duplicated default from Needs landing - Squash
    queue_conditions:
      - check-success=Bitrise
      - label=Needs Landing (Squash)
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    merge_conditions:
      - check-success=Bitrise
    merge_method: squash

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request has conflicts when rebasing. Could you fix it @{{author}}? 🙏
  - name: Bitrise update - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=bitrise.yml
      - -files~=^(?!bitrise.yml).+$
      - head=update-br-new-xcode-version
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
  - name: Rust Component Upgrade - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=Client.xcodeproj/project.pbxproj
      - files=Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
  - name: L10N - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files~=^.+\.strings$
      - -files~=^(?!^.+\.strings).+$
    actions:
      review:
        type: APPROVE
        message: LGTM 😎
  - name: Bitrise update - Auto Merge + L10N - Auto Merge + Needs landing - Rebase + Needs landing
      - Squash + Rust Component Upgrade - Auto Merge
    conditions: []
    actions:
      queue:
