name: Create a PR to build the app using newest a-s version available
on:
  schedule:
    - cron: '* 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./test-fixtures/requirements.txt
    - name: Modifing Cartfile
      run: |
        python ./test-fixtures/update_application_services_version.py
    - name: Get new A-S tag to be used in the PR info
      run: |
        cd test-fixtures/
        chmod u+x read_tag_test.sh
        echo "version=$(./read_as_tag.sh)" >> $GITHUB_ENV
    - name: Remove temp file created to store the tag info
      run: |
        cd test-fixtures/
        [ ! -e newest_tag.txt ] || rm newest_tag.txt
    - name: Update A-S release in Cartfile
      run: |-
        git diff
        git config --global user.email "firefox-test-engineering@mozilla.com"
        git config --global user.name "Firefox Test Engineering"
        git diff --quiet || (git add Cartfile Cartfile.resolved)
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Auto update Cartfile with latest A-S release ${{ env.version }}
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: Auto Update Cartfile with latest A-S version ${{ env.version }}
        branch: update-cartfile-new-as-tag-${{ env.version }}
        labels: Do Not Merge ⛔️
        token: ${{ secrets.GITHUB_TOKEN }}
