name: Build and Run Autofill Automation
permissions: read-all
on: 
  pull_request:
    paths:
      - 'firefox-ios/firefox-ios-tests/**'
      - './github/workflows/**'
jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.9]
        xcode: ["15.2"]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install node
          uses: actions/setup-node@v4
          with:
           node-version: 18

        - name: Install Playwright
          run: npx playwright install

        - name: Clone repository
          run: |
            git clone https://github.com/issammani/test-playwright.git
            cd test-playwright

        - name: Run tests
          run: |
            npm i && test